name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Clean install dependencies and build
        run: |
          cd ./webApp
          npm ci
          npm run build

      - name: Zip up Web App
        run: |
          cd ./webApp
          zip -r ../deployment/webApp.zip * -x './src/*'

      - name: Zip up build artifact
        run: zip -r build.zip * -x './webApp/*'

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Generate tag environment variable
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Generate release filename
        run: mv build.zip team-request-app-${{ env.TAG }}.zip

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "team-request-app-v*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
